- package-lock.json
- package.json
- src/compile/core/CompilationFilesManager.ts
- src/compile/dependencies/Resolver.ts
- src/index.ts
> Fix bugs with JS projects

- README.md
- package-lock.json
- package.json
- src/compile/core/CircomCompiler.ts
- src/compile/core/CircomCompilerFactory.ts
- src/compile/core/CompilationProcessor.ts
- src/config/config.ts
- src/index.ts
- src/reporter/Reporter.ts
- src/types/compile/core/circom-compiler.ts
- src/types/utils.ts
- src/types/zkit-config.ts
- src/utils/utils.ts
- test/integration/setup/config.ts
- test/unit/compile/core/circom-compiler-factory.test.ts
- test/unit/compile/core/circom-compiler.test.ts
> Add native Circom compiler support

- package-lock.json
- package.json
- src/index.ts
> Fix bug with short circuit name in the getCircuit function

- .github/workflows/release.yml
- .github/workflows/tests.yml
- scripts/versions.sh
> Release CI

- .github/actions/setup/action.yml
> Added missing action

- package-lock.json
- package.json
> Update versions of the `@solarity/zkit` and `@solarity/zktype` packages

- package-lock.json
- package.json
- src/constants.ts
> Fix include reg exp

- README.md
- package-lock.json
- package.json
- src/config/config.ts
- src/constants.ts
- src/core/compile/CompilationFilesResolver.ts
- src/core/compile/CompilationProcessor.ts
- src/core/compile/TypeGenerationProcessor.ts
- src/core/compiler/CircomCompiler.ts
- src/errors.ts
- src/index.ts
- src/reporter/Reporter.ts
- src/reporter/SpinnerProcessor.ts
- src/types/core/compile/compilation-processor.ts
- src/types/core/compiler/circom-compiler.ts
- src/types/tasks.ts
- src/types/zkit-config.ts
- test/integration/setup/config.ts
- test/unit/cache/circuits-compile-cache.test.ts
- test/unit/compile/core/circom-compiler-factory.test.ts
- test/unit/compile/core/circom-compiler.test.ts
> Update compiler errors handling

- README.md
- package-lock.json
- package.json
- src/config/config.ts
- src/index.ts
- src/reporter/Reporter.ts
- src/types/tasks.ts
- src/types/zkit-config.ts
- test/fixture-projects/hardhat-project-defined-config/hardhat.config.ts
- test/integration/setup/config.ts
> Bump zkit version

- README.md
- package-lock.json
- package.json
- src/config/config.ts
- src/constants.ts
- src/core/compile/CompilationProcessor.ts
- src/core/compiler/CircomCompiler.ts
- src/core/compiler/CircomCompilerDownloader.ts
- src/core/compiler/CircomCompilerFactory.ts
- src/core/compiler/versioning.ts
- src/core/utils/PtauDownloader.ts
- src/core/utils/VersionManagement.ts
- src/core/utils/versioning.ts
- src/index.ts
- src/reporter/Reporter.ts
- src/types/core/compile/compilation-processor.ts
- src/types/core/compiler/circom-compiler-downloader.ts
- src/types/core/compiler/circom-compiler-factory.ts
- src/types/core/compiler/circom-compiler.ts
- src/types/core/compiler/index.ts
- src/types/zkit-config.ts
- src/utils/utils.ts
- test/fixture-projects/hardhat-project-defined-config/hardhat.config.ts
- test/integration/setup/config.ts
- test/unit/compile/core/circom-compiler-factory.test.ts
> Compiler management

- README.md
- package-lock.json
- package.json
- src/cache/schemas/setup-schemas.ts
- src/config/config.ts
- src/core/compile/CompilationProcessor.ts
- src/core/compiler/CircomCompilerFactory.ts
- src/core/setup/SetupProcessor.ts
- src/index.ts
- src/types/core/setup/setup-processor.ts
- src/types/zkit-config.ts
- test/fixture-projects/hardhat-project-circuits-with-libraries/hardhat.config.ts
- test/fixture-projects/hardhat-project-defined-config/hardhat.config.ts
- test/fixture-projects/hardhat-project-with-circuits/hardhat.config.ts
- test/fixture-projects/hardhat-project-with-complex-circuits/hardhat.config.ts
- test/integration/setup/config.ts
- test/unit/cache/circuits-setup-cache.test.ts
- test/unit/compile/core/circom-compiler-factory.test.ts
> Config structure and factory singleton changes

- package-lock.json
- package.json
- src/cache/CircuitsCompileCache.ts
- src/core/setup/SetupProcessor.ts
> Use fsExtra instead of fs. Use outputFileSync function

- src/artifacts/CircuitArtifacts.ts
- src/cache/CircuitsCompileCache.ts
- src/cache/CircuitsSetupCache.ts
- src/cache/schemas/compile-schemas.ts
- src/core/compile/CompilationFilesResolver.ts
- src/core/compile/CompilationProcessor.ts
- src/core/compile/TypeGenerationProcessor.ts
- src/core/compiler/CircomCompiler.ts
- src/core/compiler/CircomCompilerDownloader.ts
- src/core/compiler/CircomCompilerFactory.ts
- src/core/dependencies/parser/CircomFilesParser.ts
- src/core/dependencies/parser/CircomFilesVisitor.ts
- src/core/dependencies/parser/CircomTemplateInputsVisitor.ts
- src/core/setup/SetupFilesResolver.ts
- src/core/setup/SetupProcessor.ts
- src/errors.ts
- src/index.ts
- src/reporter/ReporterFacade.ts
- src/utils/utils.ts
> Add doc comments

- README.md
- package-lock.json
- package.json
- src/cache/BaseCache.ts
- src/cache/CircuitsCompileCache.ts
- src/cache/CircuitsSetupCache.ts
> Fix remappings

- package-lock.json
- src/core/compiler/CircomCompiler.ts
- src/core/compiler/CircomCompilerFactory.ts
- test/fixture-projects/hardhat-project-circuits-with-libraries/.gitignore
- test/unit/core/compile/circom-compiler.test.ts
> Fix unit tests

- package-lock.json
- package.json
> Updated circom-parser

- README.md
- src/config/config.ts
- src/index.ts
- src/types/core/compiler/circom-compiler.ts
- src/types/tasks.ts
- src/types/zkit-config.ts
- test/constants.ts
- test/fixture-projects/hardhat-project-defined-config/hardhat.config.ts
- test/fixture-projects/hardhat-project-with-constraint-simplification/.gitignore
- test/fixture-projects/hardhat-project-with-constraint-simplification/circuits/ComplexCircuitWithSimplifications.circom
- test/fixture-projects/hardhat-project-with-constraint-simplification/hardhat.config.ts
- test/fixture-projects/hardhat-project-with-constraint-simplification/package.json
- test/integration/setup/config.ts
- test/integration/tasks.test.ts
- test/unit/core/compile/circom-compiler.test.ts
> Optimization flags

- package-lock.json
- package.json
- src/cache/schemas/compile-schemas.ts
- src/core/dependencies/parser/CircomTemplateInputsVisitor.ts
> Fix compile cache schema

- package-lock.json
- package.json
- src/cache/schemas/compile-schemas.ts
> Fix compile cache

- package-lock.json
- package.json
- src/cache/BaseCache.ts
- src/cache/schemas/compile-schemas.ts
- src/core/dependencies/CircomFilesResolver.ts
- src/types/core/dependencies/parser/circom-files-visitor.ts
- test/fixture-projects/hardhat-project-with-circuits/mock-circuits/newMul2.circom
- test/integration/tasks.test.ts
- test/unit/cache/circuits-compile-cache.test.ts
> Add context of the resolved circuit to the cache

- package-lock.json
- package.json
> Bump circom parser version

- package-lock.json
- package.json
> Bump zktype version

- package-lock.json
- package.json
> Fix issue with false positive resolution in if statement in circom parser

- package-lock.json
- package.json
> Bump parser version (quo operations and parentheses in expressions)

- package-lock.json
- package.json
- src/cache/schemas/compile-schemas.ts
- src/core/compile/CompilationFilesResolver.ts
- src/core/compile/CompilationProcessor.ts
- src/core/dependencies/CircomFilesResolver.ts
- src/core/dependencies/parser/CircomFilesParser.ts
- src/core/dependencies/parser/CircomFilesVisitor.ts
- src/types/core/dependencies/parser/circom-files-visitor.ts
> The cook was high

- package-lock.json
- package.json
- src/utils/path-utils.ts
> Fix filtering on Windows OS

- package-lock.json
- package.json
- src/cache/BaseCache.ts
> Fix JSON stringfy function for the bitInt type

- package-lock.json
- package.json
- src/utils/utils.ts
> Bump zkit and zktype versions to add support for calldata structs

- .eslintignore
- package-lock.json
- package.json
- src/core/zkit/CircuitZKitBuilder.ts
- test/fixture-projects-js/hardhat-project-js-with-circuits/.gitignore
- test/fixture-projects-js/hardhat-project-js-with-circuits/circuits/base/mul2Base.circom
- test/fixture-projects-js/hardhat-project-js-with-circuits/circuits/base/sumMul.circom
- test/fixture-projects-js/hardhat-project-js-with-circuits/circuits/main/Multiplier3Arr.circom
- test/fixture-projects-js/hardhat-project-js-with-circuits/circuits/main/mul2.circom
- test/fixture-projects-js/hardhat-project-js-with-circuits/hardhat.config.js
- test/fixture-projects-js/hardhat-project-js-with-circuits/package.json
- test/fixture-projects-js/hardhat.config.js
- test/helpers.ts
- test/integration/setup/config.ts
- test/integration/tasks.test.ts
- test/unit/cache/circuits-compile-cache.test.ts
- test/unit/cache/circuits-setup-cache.test.ts
- test/unit/core/compile/circom-compiler-downloader.test.ts
- test/unit/core/compile/circom-compiler-factory.test.ts
- test/unit/core/compile/circom-compiler.test.ts
- test/unit/core/compile/compilation-files-resolver.test.ts
- test/unit/core/compile/types-generation.test.ts
- test/unit/core/dependencies/file-parser.test.ts
- test/unit/core/utils/ptau-downloader.test.ts
- test/unit/core/zkit/circuit-zkit-builder.test.ts
> Fix verifiers generation bug on JS projects

- package-lock.json
- package.json
- src/constants.ts
- src/core/utils/PtauDownloader.ts
> Update zkit & zktype versions; change ptau files url prefix

- src/core/compiler/vendor/wasi.js
- test/unit/core/dependencies/file-parser.test.ts
> chore: fix some typos in comment

- README.md
- package-lock.json
- package.json
- src/constants.ts
- test/unit/core/compile/circom-compiler-factory.test.ts
> Added circom versions 2.2.1 and 2.2.2
